name: "setup"
description: "Setups App Version, JDK and Gradle for the project"
author: "Henry Addo"

inputs:
  java-version:
    description: "Java version"
    default: "21"
  java-distribution:
    description: "Java distribution"
    default: "zulu"

runs:
  using: "composite"
  steps:
    - name: Validate Gradle Wrapper
      uses: gradle/actions/wrapper-validation@v4
    - name: Setup JDK ${{ inputs.java-version }} from ${{ inputs.java-distribution }} distribution
      uses: actions/setup-java@v4
      with:
        distribution: ${{ inputs.java-distribution }}
        java-version: ${{ inputs.java-version }}
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: wrapper
    - name: Setup Konan cache key # Kotlin native dependencies
      id: konan-cache-key
      shell: bash
      run: echo "KOTLIN_VERSION=$(grep -oE 'kotlin\s*=\s*"[0-9.]*"' gradle/libs.versions.toml | grep -oE '[0-9.]+')" >> $GITHUB_OUTPUT

    - name: Cache Konan # Kotlin native dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.konan
        key: v1-konan-${{ runner.os }}-${{ hashFiles('.sdkmanrc') }}-${{ steps.konan-cache-key.outputs.KOTLIN_VERSION }}
    - name: Setup App Version Number
      shell: bash
      run: |
        echo "VERSION_NAME=$(./gradlew -q --no-configuration-cache  printVersionName)" >> $GITHUB_ENV
